spring:
  datatsource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블 만들어주는 버전(애플리케이션 실행 시점에 테이블 다 지우고 다시 생성)
    properties:
      hibernate:
        #show_sql
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #JPA, 하이버네이트가 실행하는 sql이 보이게 해주는 것(로그로)
    org.hibernate.type: trace # 파라미터 보여줌1