server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # 유레카 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지를 설정하는 속성. true면 갱신된 정보를 받는다.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #서버의 위치가 어딘지 항목 지정
